### ISSUE TITLE
Stash的去广告重写规则应该拿Surge的改

### ISSUE THREAD

**Issue by Infatuation-Fei** [QuentinHsu/network-rules#2]
QuantumultX的规则有reject-dict等特殊的，而Stash与Surge一样只有reject，Stash整个软件的设计都是更偏向Surge的🌚
不过blackmatrix7本人那里也有了Stash的覆写规则了
![Screenshot_20220729_135205_edit_193734645728020](https://user-images.githubusercontent.com/58471624/181692060-a9668460-cbf4-4ebf-a904-80787898ea52.png)

**Comment by QuentinHsu** [comment]
刚刚看了下，b7 大佬的 Stash 覆写依旧是一律 reject

- Stash：https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/Stash/AdvertisingLite/AdvertisingLite.stoverride#L145

- QuantumultX：
https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/QuantumultX/AdvertisingLite/AdvertisingLite.conf#L202

- Surge 依旧是所有一律 reject
https://github.com/blackmatrix7/ios_rule_script/blob/master/rewrite/Surge/AdvertisingLite/AdvertisingLite.sgmodule#L146

**Comment by Infatuation-Fei** [comment]
就是啊，Surge和Stash都是只支持reject，所有说你的仓库里的Stash的去广告覆写应该拿Surge的改，而不是用QuantumultX的
![Screenshot_20220729_141744](https://user-images.githubusercontent.com/58471624/181695282-660d9c0e-5940-452f-a217-a0a065541a61.png)

**Comment by QuentinHsu** [comment]
> 就是啊，Surge和Stash都是只支持reject，所以说你的仓库里的Stash的去广告覆写应该拿Surge的改，而不是用QuantumultX的 ![Screenshot_20220729_141744](https://user-images.githubusercontent.com/58471624/181695282-660d9c0e-5940-452f-a217-a0a065541a61.png)

所以，我贴出了同一个正则内容的在三种 app 格式文件的行链接，你可以看看具体的内容：
https://github.com/QuentinHsu/network-rules/issues/2#issuecomment-1198913980

**Comment by Infatuation-Fei** [comment]
不知道是我没理解你的意思还是你没理解我的意思😂
我主要是看到你这个Stash覆写是用的blackmatrix7的QuantumultX规则改来的，
![Screenshot_20220729_165039_edit_204373797261566](https://user-images.githubusercontent.com/58471624/181722463-2d7b0613-7b09-4038-99eb-66e5c7e8aa8e.png)
但他这里面包含很多像reject-dict等Stash并不支持的规则，所以才说应该拿那个Surge的规则来改
